# /etc/fail2ban/filter.d/gin.conf

[Definition]
failregex = \[GIN\]\s+\d{4}\/\d{2}\/\d{2}\s+-\s+\d{2}:\d{2}:\d{2}\s+\|\s+(?!200|302)\d{3}\s+\|\s+(?:\d{1,10}\.\d{1,10})?\d{0,3}(\w+|\W+\w+)\s+\|\s+<HOST>
# failregex = \[GIN\]\s+\d{4}\/\d{2}\/\d{2}\s+-\s+\d{2}:\d{2}:\d{2}\s+\|\s+(?!200|302)\d{3}\s+\|\s+\d{1,10}\.\d{1,10}(\w+|\W+\w+)\s+\|\s+<HOST>

ignoreregex =