# /etc/fail2ban/jail.d/gin.conf

[gin]
port = 65501
# 过滤规则filter的名字，对应filter.d目录下的sshd.conf
filter = gin
# 日志修改检测机制（gamin、polling和auto这三种）
backend=auto
# 是否激活此项（true/false）
enabled=true

# 动作的相关参数
banaction = gin

# 检测的系统的登陆日志文件
logpath = /docker/MDM/logs/app.log
# 禁止30分钟
bantime = 30m
# 这个时间段内超过规定次数会被ban掉
findtime = 1m
# 最大尝试次数
maxretry = 2